apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/thestormforge/examples/voting-webapp/application
  - hpa.yaml
  - experiment.yaml

configMapGenerator:
- name: locustfile
  files:
  - locustfile.py

generatorOptions:
  disableNameSuffixHash: true
